export const AGENT_CALL_TIMEOUT_MS = 120_000
export const LANGUAGE_CLASSIFIER_TIMEOUT_MS = 60_000
export const CORRECTION_ANALYSIS_GRACE_MS = AGENT_CALL_TIMEOUT_MS + 30_000
export const CORRECTION_AUTO_RETRY_DELAY_MS = 2_000
export const CORRECTION_MAX_AUTOMATIC_ATTEMPTS = 2
